---
image: vaultwarden
version: v0.5.37
name: vaultwarden
description: "[Vaultwarden](https://github.com/dani-garcia/vaultwarden) Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs."
ext_release: "1.35.0-alpine@sha256:daace46f8392d7e4ea48e8c2c34f78b8ecc8cee313586c656396d30523493f54"
arch:
  - aarch64
  - x86_64
  - armv7
