---
image: vaultwarden
version: v0.5.34
name: vaultwarden
description: "[Vaultwarden](https://github.com/dani-garcia/vaultwarden) Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs."
ext_release: "1.34.3-alpine@sha256:d70118b9dafb8588ee2651ceb5df68db27dcbd8e18467722010644ba48d5d6d6"
arch:
  - aarch64
  - x86_64
  - armv7
