---
image: vaultwarden
version: v0.5.41
name: vaultwarden
description: "[Vaultwarden](https://github.com/dani-garcia/vaultwarden) Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs."
ext_release: "1.35.2-alpine@sha256:dc364d362273e5604b13b02059dc98d60471e885c0a831e26be6c05ed5d488d0"
arch:
  - aarch64
  - x86_64
  - armv7
