name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
jobs:
  permission_check:
    uses: chukysoria/workflows/.github/workflows/init-svc-executable-permissions.yml@512ec689f489f3ee7c880bdb8a0b8618f5b00be4 # v1.1.20
