name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
jobs:
  permission_check:
    uses: chukysoria/workflows/.github/workflows/init-svc-executable-permissions.yml@1e7ebebec654777dc927b4fd74ca815175d356aa # v1.1.24
